name: First Workflow

on: push

jobs:
  my-first-job:
    runs-on: ubuntu-latest

    steps:
      - name: Print a message
        run: echo "Hellow from my first github action"

      - name: Check linting
        run: echo "Lingting checking..."
      
